// Static project data from GitHub repositories
// Generated by admin.html - DO NOT EDIT MANUALLY
const projects = [
    {
        "name": "risk-divergence",
        "description": "Real-time risk divergence analysis tool for financial markets",
        "url": "https://github.com/jonsflow/risk-divergence",
        "homepageUrl": "",
        "primaryLanguage": "JavaScript",
        "hasGitHubPages": true,
        "featured": true,
        "category": "financial",
        "topics": [],
        "updatedAt": "2026-03-06T21:08:14Z"
    },
    {
        "name": "bikecheck",
        "description": "iOS maintenance companion app with Strava integration for tracking bike service schedules, component maintenance, and smart reminders across multiple bikes",
        "url": "https://github.com/jonsflow/bikecheck",
        "homepageUrl": "",
        "primaryLanguage": "Swift",
        "hasGitHubPages": false,
        "featured": true,
        "category": "mobile",
        "topics": [],
        "updatedAt": "2026-03-04T05:19:42Z"
    },
    {
        "name": "schwab_streaming_options",
        "description": "Streaming options data and analysis using Schwab API",
        "url": "https://github.com/jonsflow/schwab_streaming_options",
        "homepageUrl": "",
        "primaryLanguage": "Python",
        "hasGitHubPages": false,
        "featured": true,
        "category": "devops",
        "topics": [],
        "updatedAt": "2026-02-28T04:54:10Z"
    },
    {
        "name": "rh_web",
        "description": "Web interface for Robinhood trading data and portfolio visualization",
        "url": "https://github.com/jonsflow/rh_web",
        "homepageUrl": "",
        "primaryLanguage": "Python",
        "hasGitHubPages": false,
        "featured": true,
        "category": "financial",
        "topics": [],
        "updatedAt": "2026-01-25T03:55:52Z"
    },
    {
        "name": "bragging-rights",
        "description": "Platform for sharing achievements and accomplishments",
        "url": "https://github.com/jonsflow/bragging-rights",
        "homepageUrl": "",
        "primaryLanguage": "PHP",
        "hasGitHubPages": false,
        "featured": true,
        "category": "web",
        "topics": [],
        "updatedAt": "2025-07-16T22:09:38Z"
    },
    {
        "name": "nplusone",
        "description": "iOS app prototype to track your bike fleet - because N+1 bikes is always the right number for cycling enthusiasts",
        "url": "https://github.com/jonsflow/nplusone",
        "homepageUrl": "",
        "primaryLanguage": "Swift",
        "hasGitHubPages": false,
        "featured": true,
        "category": "mobile",
        "topics": [],
        "updatedAt": "2024-12-24T02:16:30Z"
    },
    {
        "name": "resume-creator",
        "description": "A dynamic resume creation project with YAML-based configuration and modern web technologies",
        "url": "https://github.com/jonsflow/resume-creator",
        "homepageUrl": "",
        "primaryLanguage": "HTML",
        "hasGitHubPages": true,
        "featured": false,
        "category": "tools",
        "topics": [],
        "updatedAt": "2025-12-23T22:39:17Z"
    },
    {
        "name": "mamba_signals",
        "description": "Market signal generation using Mamba state space models for trading",
        "url": "https://github.com/jonsflow/mamba_signals",
        "homepageUrl": "",
        "primaryLanguage": "Python",
        "hasGitHubPages": false,
        "featured": false,
        "category": "financial",
        "topics": [],
        "updatedAt": "2025-11-30T21:11:32Z"
    },
    {
        "name": "FlowerOfLife",
        "description": "Geometric art and visualization project",
        "url": "https://github.com/jonsflow/FlowerOfLife",
        "homepageUrl": "",
        "primaryLanguage": "HTML",
        "hasGitHubPages": false,
        "featured": false,
        "category": "web",
        "topics": [],
        "updatedAt": "2025-11-08T19:34:10Z"
    },
    {
        "name": "mayan-codex",
        "description": "Mayan calendar and numerical system explorer",
        "url": "https://github.com/jonsflow/mayan-codex",
        "homepageUrl": "",
        "primaryLanguage": "HTML",
        "hasGitHubPages": false,
        "featured": false,
        "category": "web",
        "topics": [],
        "updatedAt": "2025-11-08T19:31:55Z"
    },
    {
        "name": "schwab-streaming",
        "description": "Real-time financial market data streaming application using Schwab API",
        "url": "https://github.com/jonsflow/schwab-streaming",
        "homepageUrl": "",
        "primaryLanguage": "Python",
        "hasGitHubPages": false,
        "featured": false,
        "category": "web",
        "topics": [],
        "updatedAt": "2025-11-26T13:08:02Z"
    },
    {
        "name": "YesChef",
        "description": "Menu recipe prototype for back of the house reference - Restaurant kitchen management tool",
        "url": "https://github.com/jonsflow/YesChef",
        "homepageUrl": "",
        "primaryLanguage": "HTML",
        "hasGitHubPages": true,
        "featured": false,
        "category": "tools",
        "topics": [],
        "updatedAt": "2025-07-17T23:23:29Z"
    },
    {
        "name": "mtb-trivia",
        "description": "Mountain Bike Trivia Game - Test your MTB knowledge with three difficulty levels",
        "url": "https://github.com/jonsflow/mtb-trivia",
        "homepageUrl": "",
        "primaryLanguage": "HTML",
        "hasGitHubPages": true,
        "featured": false,
        "category": "web",
        "topics": [],
        "updatedAt": "2025-07-10T01:58:08Z"
    }
];

// Function to get projects by category
function getProjectsByCategory(category) {
    if (category === 'all') {
        return projects;
    }
    return projects.filter(project => project.category === category);
}

// Function to get featured projects
function getFeaturedProjects() {
    return projects.filter(project => project.featured);
}

// Function to format date
function formatDate(dateString) {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
    });
}

// Function to get language color (for visual consistency)
function getLanguageColor(language) {
    const colors = {
        'HTML': '#e34c26',
        'Python': '#3776ab',
        'Swift': '#fa7343',
        'JavaScript': '#f1e05a',
        'TypeScript': '#2b7489',
        'Jupyter Notebook': '#da5b0b',
        'PHP': '#777bb4'
    };
    return colors[language] || '#6c757d';
}
